# Generated by Django 4.0.2 on 2022-02-10 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
